### PR TITLE
Packit Test

### PR DESCRIPTION
**Pull request by LorbusChris**

### CODE REVIEW

**Comment by TomasTomecek** [comment]
tried locally, and `packit srpm` worked just fine and even `mock --rebuild $SRPM` started the build process.

It feels like that packit-service is not hooked in this repo - is it installed?

**Comment by LorbusChris** [comment]
It is installed. Just removed and added it again, but still doesn't seem to work. Maybe it's because this is a fork?

**Comment by TomasTomecek** [comment]
okay, packit service is getting the requests but this is the problem:
```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)                                                                                                            
  cmdline: git clone --tags -v https://github.com/LorbusChris/origin.git /sandcastle                                                                                         
  stderr: 'Cloning into '/sandcastle'...                                                                                                                                     
POST git-upload-pack (gzip 5477 to 2788 bytes)                                                                                                                               
fatal: write error: No space left on device 
fatal: index-pack failed
```

**Comment by TomasTomecek** [comment]
within a few weeks, we are planning to migrate the packit service to a new cluster where storage shouldn't be a problem - would you be okay with waiting or should we fix our storage now?

**Comment by LorbusChris** [comment]
This is a blocker for OKD on FCOS. Not immediate priority, but the sooner the better :)

Some context:
I only need to run packit once on this fork in order to verify that it works, but I'll need to it set up for the main `openshift/origin` and `oc` repos asap, go get continuous builds of them (we can probably go with just COPR PR and master builds for a start (I hope), but in the longer run what we really need is a packit-service trigger for koji builds of master).
If it works here as expected, I'll work on getting packit added to the openshift org.
I am unsure how much resource consumption CI builds from those two repos will generate, btw.

**Comment by cgwalters** [comment]
> This is a blocker for OKD on FCOS. Not immediate priority, but the sooner the better :)

Is it?  We can build RPMs anywhere...among them, api.ci for example.

**Comment by LorbusChris** [comment]
Are you suggesting to add a job on OpenShift's prow?
We could do that.

Wondering though, would all the build info be publicly visible?

**Comment by cgwalters** [comment]
> Are you suggesting to add a job on OpenShift's prow?

Yep.

> Wondering though, would all the build info be publicly visible?

Yes.

**Comment by LorbusChris** [comment]
I'll look into Prow for PR CI builds.

I'm not sure if we can have per commit/timed builds of master there as well (that's what's done in ART for RHELCOS RPMs AIUI).

I would still like master builds in Koji via Packit-Service, but if that isn't possible at the moment due to resource constraints, I'm sure we can find a way to promote a CI build from Prow for use in FCOS composes somehow.

**Comment by TomasTomecek** [comment]
> I would still like master builds in Koji via Packit-Service

We don't support that right now.

**Comment by LorbusChris** [comment]
Right, I believe the issue for this is https://github.com/packit-service/packit-service/issues/47

**Pull request closed without merging**
